建立1維與2維張量

In [3]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()

In [4]:
#建立1維的張量(向量)
ts_X  =  tf.Variable([0.4,0.2,0.4])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [5]:
print(X.shape)

(3,)


In [7]:
#建立2維的tensor
ts_X  =  tf.Variable([[0.4,0.2,0.4]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


In [8]:
print('shape:',X.shape)

shape: (1, 3)


In [9]:
#建立2維的張量(向量)
W =  tf.Variable([[-0.5,-0.2],
                 [-0.3,-0.4],
                 [-0.5,0.2]]
                )
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array=sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3 -0.4]
 [-0.5  0.2]]


In [10]:
print('shape:',W_array.shape)

shape: (3, 2)


矩陣基本運算

In [16]:
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]]
                )
XW = tf.matmul(X,W)


In [13]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3        -0.40000004]]


矩陣加法

In [14]:
b = tf.Variable([[0.1,0.2]])
XW = tf.Variable([[-1.3,0.4]])

Sum = XW+b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum))

Sum:
[[-1.1999999  0.6      ]]


矩陣加法與乘法

In [17]:
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]]
                )
b = tf.Variable([[0.1,0.2]])
XWb = tf.matmul(X,W)+b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.1999999  0.6      ]]
